import type { Metadata } from "next";
import { Geist, Geist_Mono, Roboto } from "next/font/google";
import "./globals.css";
import "react-photo-view/dist/react-photo-view.css";
import { Toaster } from "@/shared/shadcn/components/ui/sonner";
import ClientLayout from "@/layout/client-layout";
import { TooltipProvider } from "@/shared/shadcn/components/ui/tooltip";
import { SessionProvider } from "next-auth/react";
const roboto = Roboto({ subsets: ["latin"], variable: "--font-sans" });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={roboto.variable}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <TooltipProvider>
          <SessionProvider>
            <ClientLayout>{children}</ClientLayout>
            <Toaster />
          </SessionProvider>
        </TooltipProvider>
      </body>
    </html>
  );
}
